import "server-only";

import { DISCLAIMERS } from "@/lib/disclaimers";
import { formatCostUsd } from "@/lib/llm/cost";
import { mapLinesOutsideFences } from "@/lib/markdown";

import type { CourseResult, GeneratedLesson, LessonOutcome } from "./runCourse";

/** "How black holes work!" -> "how-black-holes-work". Falls back to "course". */
export function slugify(topic: string, maxLength = 60): string {
  const slug = topic
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, maxLength)
    .replace(/-+$/, "");
  return slug || "course";
}

export function formatPercent(rate: number | null): string {
  return rate === null ? "n/a" : `${Math.round(rate * 100)}%`;
}

/** Bumps markdown headings down so lesson content nests under the lesson heading. Code blocks are left alone. */
export function demoteHeadings(md: string, levels: number): string {
  return mapLinesOutsideFences(md, (line) =>
    line.replace(/^(#{1,6}) /, (_, hashes: string) => `${"#".repeat(Math.min(6, hashes.length + levels))} `),
  );
}

function renderLesson(lesson: GeneratedLesson): string[] {
  const { spec, slot, content, factCheck } = lesson;
  const out: string[] = [];
  const label = spec.kind === "review" ? "Review" : `Lesson ${lesson.position + 1}`;
  out.push(`### ${label}: ${spec.title}`);
  out.push(
    `*${slot.estMinutes} min: reading ${slot.readingMinutes}, videos ${slot.mediaMinutes}, practice and quiz ${slot.practiceMinutes}*`,
  );
  out.push(`**Objectives**\n${spec.objectives.map((o) => `- ${o}`).join("\n")}`);
  if (factCheck.unverifiedClaims.length) {
    out.push(
      `> ⚠️ **Some claims could not be verified.** Double-check these before relying on them:\n` +
        factCheck.unverifiedClaims.map((i) => `> - ${i.claim}`).join("\n"),
    );
  }
  out.push(demoteHeadings(content.contentMd.trim(), 2));
  if (lesson.videos.length) {
    out.push(`#### Videos\n${lesson.videos.map((v) => `- [${v.title}](${v.url}) (${v.excerpt})`).join("\n")}`);
  }
  if (content.keyTerms.length) {
    out.push(`#### Key terms\n${content.keyTerms.map((t) => `- **${t.term}**: ${t.definition}`).join("\n")}`);
  }
  if (content.practiceTask) {
    out.push(`#### Practice\n${content.practiceTask.instructions}\n\n*Expected outcome:* ${content.practiceTask.expectedOutcome}`);
  }
  const questions = lesson.quiz.questions.map(
    (q, i) => `${i + 1}. ${q.prompt}\n${q.options.map((o) => `   - ${o.id}) ${o.text}`).join("\n")}`,
  );
  const answers = lesson.quiz.questions.map((q, i) => {
    const correct = q.options.find((o) => o.id === q.correctOptionId);
    return `${i + 1}. **${q.correctOptionId}) ${correct?.text ?? ""}**: ${q.explanation}`;
  });
  out.push(`#### Quiz\n${questions.join("\n")}\n\n<details><summary>Answers</summary>\n\n${answers.join("\n")}\n\n</details>`);
  out.push(`#### Sources\n${lesson.sources.map((s) => `${s.index}. [${s.title}](${s.url})`).join("\n")}`);
  return out;
}

function renderOutcome(outcome: LessonOutcome): string[] {
  if (outcome.status === "ready") return renderLesson(outcome.lesson);
  return [`### ${outcome.title}`, `> ❌ This lesson failed to generate: ${outcome.error}`];
}

/** A readable single-file course: syllabus order, lessons with citations, quizzes and linked sources. */
export function renderCourseMarkdown(course: CourseResult): string {
  const { syllabus: syllabusResult, intake, stats } = course;
  const syllabus = syllabusResult.curriculum.syllabus;
  const { plan } = syllabusResult;
  const out: string[] = [];

  out.push(`# ${syllabus.courseTitle}`);
  out.push(syllabus.courseSummary);
  out.push(
    `*${intake.days} day${intake.days === 1 ? "" : "s"} × ${intake.minutesPerDay} min · level: ${intake.level.replace("_", " ")} · ` +
      `goal: ${intake.goal.replace("_", " ")} · ${plan.topicType}*`,
  );
  if (plan.sensitiveDomain) out.push(`> **Disclaimer:** ${DISCLAIMERS[plan.sensitiveDomain]}`);

  for (const day of syllabus.days) {
    const total = day.lessons.reduce((n, l) => n + l.estMinutes, 0);
    out.push(`## Day ${day.dayNumber}: ${day.theme}`);
    out.push(`*${total} min*`);
    for (const outcome of course.lessons) {
      const dayNumber = outcome.status === "ready" ? outcome.lesson.dayNumber : outcome.dayNumber;
      if (dayNumber === day.dayNumber) out.push(...renderOutcome(outcome));
    }
  }

  out.push("---");
  out.push(
    `*Generated by CourseForge. ${stats.lessons.ready}/${stats.lessons.total} lessons ready, ` +
      `fact-check pass rate ${formatPercent(stats.lessons.factCheckPassRate)}, ${stats.llm.calls} LLM calls, ` +
      `${formatCostUsd(stats.llm.costUsd)}, ${(stats.timings.totalMs / 1000).toFixed(0)}s.*`,
  );
  return `${out.join("\n\n")}\n`;
}
